// <auto-generated />
using System;
using InterviewAi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewAi.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterviewAi.Api.Models.InterviewQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Intention")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("InterviewReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SuggestedAnswer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewReportId");

                    b.ToTable("InterviewQuestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_InterviewQuestions_Type", "[Type] IN ('Technical', 'Behavioral')");
                        });
                });

            modelBuilder.Entity("InterviewAi.Api.Models.InterviewReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchScore")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResumeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SelfDescription")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("InterviewReports", null, t =>
                        {
                            t.HasCheckConstraint("CK_InterviewReports_MatchScore", "[MatchScore] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_InterviewReports_ResumeOrSelfDescription", "[ResumeText] IS NOT NULL OR [SelfDescription] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("InterviewAi.Api.Models.PreparationDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("InterviewReportId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("Tasks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewReportId", "DayNumber")
                        .IsUnique();

                    b.ToTable("PreparationDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_PreparationDays_DayNumber", "[DayNumber] >= 1");
                        });
                });

            modelBuilder.Entity("InterviewAi.Api.Models.SkillGap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("InterviewReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewReportId");

                    b.ToTable("SkillGaps", null, t =>
                        {
                            t.HasCheckConstraint("CK_SkillGaps_Severity", "[Severity] IN ('Low', 'Medium', 'High')");
                        });
                });

            modelBuilder.Entity("InterviewAi.Api.Models.InterviewQuestion", b =>
                {
                    b.HasOne("InterviewAi.Api.Models.InterviewReport", null)
                        .WithMany("Questions")
                        .HasForeignKey("InterviewReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewAi.Api.Models.PreparationDay", b =>
                {
                    b.HasOne("InterviewAi.Api.Models.InterviewReport", null)
                        .WithMany("PreparationPlan")
                        .HasForeignKey("InterviewReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewAi.Api.Models.SkillGap", b =>
                {
                    b.HasOne("InterviewAi.Api.Models.InterviewReport", null)
                        .WithMany("SkillGaps")
                        .HasForeignKey("InterviewReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewAi.Api.Models.InterviewReport", b =>
                {
                    b.Navigation("PreparationPlan");

                    b.Navigation("Questions");

                    b.Navigation("SkillGaps");
                });
#pragma warning restore 612, 618
        }
    }
}
